### ISSUE TITLE
FG failing to submit plugin statistics.

### ISSUE THREAD

**Issue by MarkTwoFive** [FoxDenStudio/FoxGuard#82] opened 2017-04-10 18:02 UTC
* FG-Version: ``0.20.2-api5-347``
* FC-Version: ``0.10.3-208-server``
* Sponge-Version: Cloned repository: ``SpongePowered/SpongeForge`` on branch ``stable-5``

FoxGuard repeatedly fails to submit plugin statistics.
The following errors occur:
* HTTP 500 for ``http://report.mcstats.org/plugin/FoxGuard``
* HTTP 504 for ``http://report.mcstats.org/plugin/FoxGuard``
* HTTP 508 for ``http://report.mcstats.org/plugin/FoxGuard``
* Unexpected EOF from server
* Connection reset

It appears that the whole service is down or broken since a year so this "feature" may be ready to get ditched.

If any further information is required let me know.

**Comment by ghost** [comment] 2017-05-22 16:52
So at some point, we will be switching to our own stats system, in which case this error should be fixed.

If it is spamming your logs, please let me know, and I'll try to patch it out real quick, otherwise please ignore it until we decided what to do.

**Comment by BrainStone** [comment] 2017-05-22 17:45
Spams like once every 30 minutes. A fix would be nice.

**Comment by ghost** [comment] 2017-05-22 17:55
Ok, thanks for letting me know, I'll work to at least get a patch out that will prevent that.  Might take a few days though, as work is going to be insane this week.

**Comment by MarkTwoFive** [comment] 2017-05-23 15:30
@BrainStone see if disabling mcstats using its config solves this.

**Comment by gravityfox** [comment] 2017-05-23 22:06
Go to your config folder, then mcstats.properties.

Set opt-out to true and see if the problem goes away.

**Comment by gravityfox** [comment] 2018-04-07 08:39
Going to close this because the issue is ultimately due to the fact that mcstats is no longer a stable service and is basically expired. I'm removing mcstats from foxguard permanently soon, so this is no longer a concern

**Closed as completed by gravityfox** 2018-04-07 08:39 UTC
