### ISSUE TITLE
Updated SF

### ISSUE THREAD

**Issue by pocketpixelsmc** [FoxDenStudio/FoxGuard#88] opened 2017-05-22 15:45 UTC
I just updated to the newest version of SF. Now FoxGuard broke. Here is the error:

https://hastebin.com/eyavacugaq.rb

**Comment by ghost** [comment] 2017-05-22 15:59
https://github.com/FoxDenStudio/FoxGuard/releases/tag/v0.20.5-untested-hotfix

You are presumably trying to use an API5 version of FoxGuard in what is SpongeForge API6...

Please try the release linked above, and if it still doesn't work, then please give a hastebin of the ENTIRE log file, and the exact version of SpongeForge and FoxGuard that you are using.

Duplicate of #78 - Please reopen if it isn't.

**Closed as completed by ghost** 2017-05-22 15:59 UTC
