### ISSUE TITLE
Exception in thread "Server Watchdog" - Loading Regions

### ISSUE THREAD

**Issue by EmanYm** [FoxDenStudio/FoxGuard#87] opened 2017-05-19 04:45 UTC
[I have an error](https://github.com/SpongePowered/SpongeForge/issues/1522) I thought was caused by Spongeforge.  After I removed ChatUI from my mods folder the same error is now labled FoxGuard.

Here is the most recent error as it appears in the console:
>Exception in thread "Server Watchdog" [22:51:59] [Server thread/INFO] [foxguard]: Loading regions
[22:51:59] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalArgumentException: timeout value is negative
[22:51:59] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at java.lang.Thread.sleep(Native Method)
[22:51:59] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:83)
[22:51:59] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at java.lang.Thread.run(Thread.java:745)

I am wondering if this might have anything to do with it.
>[22:49:44] [Server thread/WARN] [Sponge]: The mod foxguard was designed for spongeapi 6.0.0-SNAPSHOT but version 5.2.0-SNAPSHOT-a26c654 is in use. It may not work properly.

Detected Versions
[22:49:38] [Server thread/INFO] [FML]: MinecraftForge v12.18.3.2297 Initialized
[22:49:46] [Server thread/INFO]:   Running on server version SpongeAPI: 5.2.0-SNAPSHOT-a26c654 - SpongeForge: 1.10.2-2281-5.2.0-BETA-2328
[22:51:32] [Server thread/INFO] [foxcore]: Version: 0.10.3-208
[22:51:33] [Server thread/INFO] [foxguard]: Version: 0.20.5-untested-hotfix-367

**Comment by Inscrutable** [comment] 2017-05-19 05:58
This does not look like it was caused by FoxGuard (at first glance). The Server Watchdog is kicking in during the loading of the FoxGuard regions. Something weird is going on, "timeout value is negative". Either a mod is clogging startup or something is weird with a config file. What is the max-tick-time set to in ``server-properties``?

**Comment by EmanYm** [comment] 2017-05-19 14:28
`max-tick-time=60000`

I've checked all of my configs against the examples or guides on the sites for each of the mods/plugins I'm using.  Anywhere I have a -1 claims to be allowed.

The only thing that really hangs is LuckPerms, but it did that even when it was the only thing in the mods folder.  I started to get the watchdog after Foxguard (the second thing added).
>[05:32:02] [Server thread/INFO]: [LP] Registering API...
[05:33:45] [Server thread/INFO]: [LP] Successfully loaded.

**Comment by Inscrutable** [comment] 2017-05-19 14:46
It's possible the bug may have disappeared amongst the recent sea of fixes in SpongeForge. May I suggest updating to SF build 2344 and see if it still happens.

**Comment by EmanYm** [comment] 2017-05-19 15:08
The watchdog is still watching.  It's back to "STDERR" now.

>[10:04:48] [Server thread/INFO] [foxguard]: Loading regions
Exception in thread "Server Watchdog" [10:04:48] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.IllegalArgumentException: timeout value is negative
[10:04:48] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at java.lang.Thread.sleep(Native Method)
[10:04:48] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:83)
[10:04:48] [Server Watchdog/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: at java.lang.Thread.run(Thread.java:745)
[10:04:48] [Server thread/INFO] [foxguard]: Loading global handler

It doesn't appear to be breaking anything after everything is loaded.  I will go through all of my configs again with more detail and see if I missed anything the first time.
Thanks for your time, Inscrutable.

**Comment by ghost** [comment] 2017-05-22 16:57
I am going to close this issue for now, but if you have any updates on what is/was causing this, please reply.

If it turns out to be an actual FoxGuard/FoxCore issue, I will reopen it and tag it properly.

Thanks.

**Closed as completed by ghost** 2017-05-22 16:57 UTC
