### ISSUE TITLE
ExplosionEvent IndexOutOfBoundsException

### ISSUE THREAD

**Issue by LemADEC** [FoxDenStudio/FoxGuard#77] opened 2017-03-08 01:43 UTC
As of foxcore-0.10.3-208-server.jar + foxguard-0.20.2-api5-347-server.jar + spongeforge-1.10.2-2221-5.2.0-BETA-2219.jar, there's an exception in ExplosionEvent:
```
[20:21:54] [Server thread/ERROR] [Sponge]: Could not pass ExplosionEvent$Detonate$Impl to Plugin{id=foxguard, name=FoxGuard, version=0.20.2-api5-347, description=A world protection plugin built for SpongeAPI. Requires FoxCore., url=https://github.com/FoxDenStudio/FoxGuard, authors=[gravityfox], source=/home/magmayhem/./plugins/foxguard-0.20.2-api5-347-server.jar}
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
>       at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_121]
>       at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_121]
>       at net.foxdenstudio.sponge.foxguard.plugin.listener.ExplosionListener.handle(ExplosionListener.java:127) ~[ExplosionListener.class:?]
>       at net.foxdenstudio.sponge.foxguard.plugin.listener.ExplosionListener.handle(ExplosionListener.java:53) ~[ExplosionListener.class:?]
>       at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) [SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:342) [SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) [SpongeModEventManager.class:1.10.2-2221-5.2.0-BETA-2219]
>       at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) [SpongeImpl.class:1.10.2-2221-5.2.0-BETA-2219]
>       at net.minecraft.world.Explosion.func_77278_a(Explosion.java:734) [ahy.class:?]
>       at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:3018) [ls.class:?]
>       at net.minecraft.world.World.func_72876_a(World.java:2303) [aid.class:?]
>       at lycanite.lycanitesmobs.shadowmobs.entity.EntityEpion.func_70636_d(EntityEpion.java:108) [EntityEpion.class:?]
>       at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) [sf.class:?]
>       at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) [sg.class:?]
>       at lycanite.lycanitesmobs.core.entity.EntityCreatureBase.func_70071_h_(EntityCreatureBase.java:1264) [EntityCreatureBase.class:?]
>       at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:156) [TrackingUtil.class:1.10.2-2221-5.2.0-BETA-2219]
>       at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zjn000(WorldServer.java:2810) [ls.class:?]
>       at net.minecraft.world.World.func_72866_a(World.java:4071) [aid.class:?]
>       at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839) [ls.class:?]
>       at net.minecraft.world.World.func_72870_g(World.java:1934) [aid.class:?]
>       at net.minecraft.world.World.func_72939_s(World.java:5954) [aid.class:?]
>       at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2153) [ls.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by gravityfox** [comment] 2017-03-08 01:51
I think i fixed this already

**Comment by gravityfox** [comment] 2017-03-08 01:54
Yeah this is a duplicate of #59. Closing.

**Closed as completed by gravityfox** 2017-03-08 01:54 UTC
Labels: duplicate

**Comment by LemADEC** [comment] 2017-03-08 08:52
Could we get a new release to deploy that fix?
