### ISSUE TITLE
spawn hostile =deny

### ISSUE THREAD

**Issue by WillPowerCraft** [FoxDenStudio/FoxGuard#54] opened 2016-11-24 22:27 UTC
1 case:

skeleton horses + skeletons from lighting horse:
that working like: 4 skeleton horses + 4 invisible passive skeletons who play there sounds if i stay near.

if i try kill that invisible entitys (skeletons) and all other near entitys from command
/kill @e[type=!player,r=2]

that make kill skeleton horse and error about skeletons text of error looks like:
entity 'bla-bla-bla' not found.

and that invisible undying entitys blocking transport like boats/minecarts on road.

pls fix that

//with love to your job :3
//when i start getting donate on my server i will donate you for your plugin!

**Comment by gravityfox** [comment] 2016-11-24 22:35
More sponge bugs. I'll also tell the devs about it.

I'm going to guess this is also 1.11 right? Since you're the same guy from the other two issues.

**Comment by WillPowerCraft** [comment] 2016-11-24 22:38
yeah thats 1.11 too.
if u want i can put all cases in one issue in future...

**Comment by gravityfox** [comment] 2016-11-24 22:39
That would be greatly appreciated.....

**Comment by ziceptor** [comment] 2016-11-30 10:56
We discussed it.
https://forums.spongepowered.org/t/api-5-x-6-x-foxguard-the-flexible-world-protection-solution/9952/675?u=ziceptor

**Comment by cosmic80** [comment] 2017-01-30 07:05
I'm getting the same thing and I'm running 1.10.2 on spongevanilla api 5.0. I set up a pretty large region and connected to its handler, made sure spawn hostile is set to deny, but skeleton horses and skeleton's still seem to spawn, oddly enough its only skeletons with helmets too, normal skeletons don't spawn.

**Comment by Inscrutable** [comment] 2017-01-30 07:50
Skeleton horses and their riders spawning is something that vanilla Minecraft itself stuffs up. There's a plugin to stop them from appearing, the problem is that dire. Try this: https://forums.spongepowered.org/t/disableskeletonhorse-disables-skeleton-horses-5-0-0/14732

**Comment by gravityfox** [comment] 2018-04-07 08:36
Going to close this cause it's been awhile and is probably fixed now.

**Closed as completed by gravityfox** 2018-04-07 08:36 UTC
Labels: sponge
