### ISSUE TITLE
Duplication Glitch with TNT

### ISSUE THREAD

**Issue by JBYoshi** [FoxDenStudio/FoxGuard#8] opened 2015-12-22 02:26 UTC
When someone launches TNT into a protected area which they do not have permission to change, the block changes are rejected, but the items are still dropped.

**Comment by gravityfox** [comment] 2015-12-22 02:35
The heck?

What version of foxguard and sponge forge are you using?

**Comment by JBYoshi** [comment] 2015-12-22 02:36
It's on the test server. foxguard 0.11.1, SpongeForge 951.

**Comment by gravityfox** [comment] 2015-12-22 02:39
which test server? Yours or mine?

Also use a newer version of foxguard and test. There were recent API changes that might have broken things.

**Comment by JBYoshi** [comment] 2015-12-22 02:44
It's the Sponge demo server. I'll run a test on a local client and see if the newer version fixes it.

**Comment by gravityfox** [comment] 2015-12-22 03:30
I'm not able to reproduce this bug with my own plugin in my workspace.

I think it's either sponge or another plugin

My plugin is just cancelling block break events.

What happens beyond that is not currently under my control.

**Comment by gravityfox** [comment] 2015-12-22 03:53
Also i just realized that i broke my version injection because i forgot how to regex.

The server plugin version is actually 0.12.1

Fixing that now...

**Comment by gravityfox** [comment] 2015-12-31 06:30
Closing since this issue is no longer happening. Will reopen if it crops up again.

**Closed** 2015-12-31 06:30 UTC
Labels: bug
