### ISSUE TITLE
Issues with Mob Explosions Spamming Console

### ISSUE THREAD

**Issue by Orcinuss** [FoxDenStudio/FoxGuard#61] opened 2016-12-15 08:36 UTC
Found this spamming console while players were spawning withers. I have block change explosion set to false. Not really sure what to make of it.

http://pastebin.com/Hasy8FC5

**Comment by gravityfox** [comment] 2016-12-15 08:59
Duplicate of #59, and already fixed. Thanks for reporting it anyway tho.

**Closed as completed by gravityfox** 2016-12-15 08:59 UTC
