### ISSUE TITLE
Could not pass FMLServerStartingEvent to Plugin

### ISSUE THREAD

**Issue by EmanYm** [FoxDenStudio/FoxGuard#80] opened 2017-03-26 13:24 UTC
I recently started to get this [error](http://pastebin.com/F1qL19e7) in the console after a host initiated server restart.

SpongeForge 5.2.0β2236
Forge 12.18.3.2254
FoxGuard 0.20.2β347
FoxCore 0.10.3β208

Edit:
I have always named the mods like this, since the early MC1.1 days.  It only started giving the error since the last time I updated a couple mods.  I believe FoxGuard was one of them.

**Comment by ghost** [comment] 2017-03-26 13:49
The last Sponge version that was confirmed working is 2160. Anything newer had a breaking change that affects FoxGuard.  An update fix is in progress.

**Comment by ghost** [comment] 2017-03-26 13:53
Duplicate of #78 <- will be updated when a fix is pushed.

**Closed as completed by ghost** 2017-03-26 13:53 UTC

**Comment by EmanYm** [comment] 2017-03-26 14:04
I should have known this.  /)_-
Something in the back of my head was telling me this was posted on the discord.

**Comment by ghost** [comment] 2017-04-04 21:00
@EmanYm Update posted in issue 78.

**Comment by EmanYm** [comment] 2017-04-09 09:55
@d4rkfly3r Thank you.
