### ISSUE TITLE
Could not pass LoadWorldEvent

### ISSUE THREAD

**Issue by seema84** [FoxDenStudio/FoxGuard#79] opened 2017-03-13 19:05 UTC
version v0.20.2-api5
sponge vanilla 1.11.2 build 231

`[19:40:42 INFO] [foxguard]: World region info loaded!  Name: "regionname",  Category: "worldregion",  Type: "r
ectangular",  Enabled: true
[19:40:42 ERROR] [Sponge]: Could not pass LoadWorldEvent$Impl to Plugin{id=foxguard, name=FoxGuard, version=0.
20.2-api5-347, description=A world protection plugin built for SpongeAPI. Requires FoxCore., url=https://githu
b.com/FoxDenStudio/FoxGuard, authors=[gravityfox], source=mods\foxguard-0.20.2-api5-347-server.jar}
java.lang.NoClassDefFoundError: org/spongepowered/api/event/SpongeEventFactoryUtils
        at net.foxdenstudio.sponge.foxguard.plugin.event.util.FGEventFactory.createFGUpdateObjectEvent(FGEvent
Factory.java:43) ~[FGEventFactory.class:?]
        at net.foxdenstudio.sponge.foxguard.plugin.FGManager.addWorldRegion(FGManager.java:140) ~[FGManager.cl
ass:?]
        at net.foxdenstudio.sponge.foxguard.plugin.FGStorageManager.lambda$loadWorldRegions$6(FGStorageManager
.java:738) ~[FGStorageManager.class:?]
        at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_121]
        at net.foxdenstudio.sponge.foxguard.plugin.FGStorageManager.loadWorldRegions(FGStorageManager.java:695
) ~[FGStorageManager.class:?]
        at net.foxdenstudio.sponge.foxguard.plugin.FoxGuardMain.worldLoad(FoxGuardMain.java:257) ~[FoxGuardMai
n.class:?]
        at org.spongepowered.common.event.listener.LoadWorldEventListener_FoxGuardMain_worldLoad19.handle(Unkn
own Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredLi
stener.class:1.11.2-6.0.0-BETA-231]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:305) [SpongeEventMan
ager.class:1.11.2-6.0.0-BETA-231]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:320) [SpongeEventMan
ager.class:1.11.2-6.0.0-BETA-231]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:146) [SpongeImpl.class:1.11.2-6.0.0-B
ETA-231]
        at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:819) [World
Manager.class:1.11.2-6.0.0-BETA-231]
        at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:767) [WorldManager.clas
s:1.11.2-6.0.0-BETA-231]
        at net.minecraft.server.MinecraftServer.func_71247_a(SourceFile:3725) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:229) [lh.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:436) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: org.spongepowered.api.event.SpongeEventFactoryUtils
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper
-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        ... 17 more
Caused by: java.lang.NullPointerException`

**Comment by ghost** [comment] 2017-03-13 19:11
Duplicate of #78 - Known bug, will be fixed sometime in the near future. Last known compatible Sponge build is 2160 (which is an older version of API 5).

**Closed as completed by ghost** 2017-03-13 19:11 UTC

**Comment by ghost** [comment] 2017-04-04 21:00
@seema84 Update posted in issue 78.
