### ISSUE TITLE
[MAJOR] Won't load on startup

### ISSUE THREAD

**Issue by TooVeryIcey** [FoxDenStudio/FoxGuard#74] opened 2017-02-18 14:35 UTC
I have installed FoxGuard, and FoxCore...and have noticed that FoxGuard does not load on startup...FoxCore works fine...it is just FoxGuard that simply won't load.
A startup log is below:
https://hastebin.com/zewiyayofo.cs

**Comment by TooVeryIcey** [comment] 2017-02-18 14:39
I am using API 6

**Comment by ghost** [comment] 2017-02-18 18:01
`18.02 08:33:38 [Server] INFO [08:33:38 WARN] [Sponge]: Plugin foxcore from mods/foxcore-0.10.3-208.jar was designed for spongeapi 5.0.0-SNAPSHOT. It may not work properly.`

Also, the only error that I am seeing is 
`18.02 08:33:38 [Server] INFO Caused by: java.lang.NoClassDefFoundError: Lnet/minecrell/mcstats/SpongeStatsLite` FoxGuard/Core does use SpongeStatsLite (or we used to anyhow), and it looks like the reason that FoxGuard is failing to load, at least in this instance, is that SpongeStatsLite couldn't be injected.  That may or may not be a FoxGuard issue, and it may not be caused by using an API 5 plugin on API 6.  

Also seeing as le Fox is on hiatus due to school and life for probably the next couple months, it is doubtful that an API 6 specific version will be released soon. The Fox Suite is a massive amount of code, and most plugins do/will link together so updating is not a quick task.

I'm going to close this, as it looks like this is simply a versioning error, and not an actual bug, however if there are other details, please fell free to comment on this.

**Comment by EmanYm** [comment] 2017-02-18 18:12
Just to shed some additional light on this...
I had asked on spongepowered.org if API5 plugins would work on an API6 environment because of another plugin I wanted to use that had a bug which is fixed with a plugin update.  The only other versions of that plugin were built on API 6.  This is what Aaron had to say

>Aaron1011Lord [SpongeDeveloper]
>API 6 is intetionally not backwards compatbilie, unfortunately. Any breaking changes we make to the API will be done in the next major version (API 6 in this case).

The only exemption to this I have found is with SignEdit, it says API 6 in the mcmod.info file, and even gives the message in the console that it may not work, but it does infact work in API 5 environment.

**Comment by TooVeryIcey** [comment] 2017-02-18 19:58
So...basically there is no world guard replacement...bloody brilliant

**Comment by gravityfox** [comment] 2017-02-18 20:02
Oh uh. You probably downloaded the wrong foxguard jar.

Can you send me a screenshot of your mods folder?

I need FULL FILE NAMES.

**Comment by TooVeryIcey** [comment] 2017-02-18 20:06
![screen shot 2017-02-18 at 3 05 32 pm 2](https://cloud.githubusercontent.com/assets/9706839/23096492/ce9f1a4e-f5eb-11e6-9979-851f23959152.png)

**Comment by TooVeryIcey** [comment] 2017-02-18 20:06
Is that good enough?

P.S. I use BeastNode hosting...in case that matters

**Comment by gravityfox** [comment] 2017-02-18 20:17
you need the -server.jar for both foxcore and foxguard...

try that.

**Closed as completed by gravityfox** 2017-02-18 20:17 UTC
